#!/usr/bin/env python
# Downloads zones from czds
import requests
import json
import os
import datetime
import re

config = {
	'token':	None,
	'directory':	'output/'
}

url = {
	'base': 'https://czdap.icann.org',
	'data':	'/user-zone-data-urls.json?token='
}

s = requests.Session()

class DownloadNextException(Exception):
	pass

def sizeprefix(size):
	prefix = {0: 'B', 1: 'kB', 2: 'MB', 3: 'GB'}
	multiplier = 0
	while size > 1024:
		size /= 1024
		multiplier += 1
	return '{:>6.1f} {}'.format(size, prefix[multiplier])

def gettoken():
	global config
	tokenfile = open('config', 'r')
	config['token'] = tokenfile.readline().strip()

def makedirs(date):
	os.makedirs('{}{}'.format(config['directory'], date), exist_ok=True)

def getdataurl(s):
	print('downloading {}{}'.format(url['base'], url['data'].split('?')[0]))
	request = s.get('{}{}{}'.format(url['base'], url['data'], config['token']))
	data = list(set(json.loads(request.text)))
	return ['{}{}'.format(url['base'], elem) for elem in data]

def parseheader(r):
	ret = {}
	ret['filename'] = re.findall('filename=(.+)', r.headers['content-disposition'])[0].strip('"')
	(ret['date'], ret['zone']) = re.findall('(\d{8})-([-a-z0-9]+)-zone-data.txt.gz', ret['filename'])[0]
	if 'xn--' in ret['zone']:
		ret['zone'] = ret['zone'].encode('utf-8').decode('idna')
	ret['size'] = int(r.headers['content-length'])
	return ret

def checkdownload(h):
	try:
		s = os.path.getsize('{}{}/{}'.format(config['directory'], h['date'], h['filename']))
		if s == h['size']:
			return True
	except:
		pass
	return False

def getdata(dl, s):
	for elem in dl:
		try:
			request = s.get(elem, stream=True)
			if request.status_code != 200:
				raise DownloadNextException("request status code != 200: {}".format(request.status_code))
			header = parseheader(request)
			if checkdownload(header):
				print('[✓] {} {} .{:<20}'.format(header['date'], sizeprefix(header['size']), header['zone']))
				raise DownloadNextException("zone already downloaded")
			print('[⇓] {} {} .{:<20}'.format(header['date'], sizeprefix(header['size']), header['zone']))
			makedirs(header['date'])
			with open('{}{}/{}'.format(config['directory'],	header['date'], header['filename']), 'wb') as f:
				for chunk in request.iter_content(chunk_size=None):
					if chunk:
						f.write(chunk)
		except DownloadNextException:
			pass
		except Exception as e:
			print('SOMETHING HAPPENED: {}'.format(repr(e)))
		finally:
			request.close()

gettoken()
dl = getdataurl(s)
getdata(dl, s)
